#!/bin/sh
#
# httpdphp        Startup script for the built-in PHP server
#
# description: Built-in simple PHP server \
#	       Only one website

### BEGIN INIT INFO
# Provides:          httpdphp
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start simple http server
### END INIT INFO

. /lib/lsb/init-functions

start() {
    log_begin_msg "Starting http server"
    nohup /usr/local/sbin/httpdphp > /dev/null 2>&1 &
    log_end_msg 0
}
stop() {
    log_begin_msg "Stopping http server"
    killall php > /dev/null 2>&1
    log_end_msg 0
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit 0